const GalleryData = [
    {"images": "../images/gal1.jpg", "category":"mackup"},
    {"images": "../images/gal2.jpg", "category":"artist"},
    {"images": "../images/gal3.jpg", "category":"mackup"},
    {"images": "../images/gal4.jpg", "category":"waxing"},
    {"images": "../images/gal5.jpg", "category":"artist"},
    {"images": "../images/gal6.jpg", "category":"artist"},
    {"images": "../images/gal7.jpg", "category":"mackup"},
    {"images": "../images/gal8.jpg", "category":"artist"},
    {"images": "../images/gal9.jpg", "category":"mackup"},
    {"images": "../images/gal10.jpg", "category":"mackup"},
    {"images": "../images/gal11.jpg", "category":"waxing"},
    {"images": "../images/gal12.jpg", "category":"mackup"},
    {"images": "../images/gal13.jpg", "category":"artist"},
    {"images": "../images/gal14.jpg", "category":"mackup"},
    {"images": "../images/gal15.jpg", "category":"waxing"},
    {"images": "../images/gal16.jpg", "category":"mackup"},
    {"images": "../images/gal17.jpg", "category":"waxing"},
    {"images": "../images/gal18.jpg", "category":"mackup"},
    {"images": "../images/gal19.jpg", "category":"artist"},
    {"images": "../images/gal20.jpg", "category":"waxing"},
    {"images": "../images/gal21.jpg", "category":"mackup"},
    {"images": "../images/gal22.jpg", "category":"mackup"},
    {"images": "../images/gal23.jpg", "category":"artist"},
]
export default GalleryData